[project]
name = "raddit-script"
version = "0.1.0"
description = "raddit-script-counter"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mypy>=1.13.0",
    "praw>=7.8.1",
    "pyhocon>=0.3.61",
]
